### ISSUE TITLE
Release version 1.2.0

### ISSUE THREAD

**Issue by jeffpaul** [10up/ads-txt#43]
This issue is for tracking changes for the 1.2.0 release.  Target release date: **TBD**

### Pre-release steps
- [x] update release instructions in CONTRIBUTING.md
- [x] add CREDITS.md file with previous contributors, listing current maintainers
- [x] review #19 to see if it's viable for the release, if so ensure it's updated to `develop` and then merge
- [x] review #29 to see if it's viable for the release, if so ensure it's updated to `develop` and then merge
- [x] review #42 to see if it's viable for the release, , if so ensure it's updated to `develop` and then merge
- [x] test `develop` against WordPress 5.3, assuming all goes well, update the "tested up to" value to 5.3

### [Release steps](https://github.com/10up/ads-txt/blob/develop/CONTRIBUTING.md#release-instructions)

- [x] Branch: Starting from `develop`, cut a release branch named `release/1.2.0` for your changes.
- [x] Version bump: Bump the version number in `ads-txt.php` and `readme.txt` if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in both `readme.txt` and `CHANGELOG.md`.
- [x] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.gitattributes`.
- [x] Readme updates: Make any other readme changes as necessary. `CHANGELOG.md` and `README.md` are geared toward GitHub and `readme.txt` contains WordPress.org-specific content. The two are slightly different.
- [x] Merge: Make a non-fast-forward merge from `develop` to `master` (`git checkout master && git merge --no-ff develop`).
- [x] Release: Create a [new release](https://github.com/10up/ads-txt/releases/new), naming the tag and the release with the new version number, and targeting the `master` branch. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the milestone (e.g. `https://github.com/10up/ads-txt/milestone/1?closed=1`).
- [x] SVN: Wait for the [GitHub Action](https://github.com/10up/ads-txt/actions) to finish deploying to the WordPress.org repository. If all goes well, users with SVN commit access for that plugin will receive an emailed diff of changes.
- [x] Check WordPress.org: Ensure that the changes are live on [https://wordpress.org/plugins/ads-txt/](https://wordpress.org/plugins/ads-txt/). This may take a few minutes.
- [x] Close milestone: Edit the [1.2.0 milestone](https://github.com/10up/ads-txt/milestone/12) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `1.2.0` do not make it into the release, update their milestone to `1.3.0` or `Future Release`.
